Make the call to recv on the telnet connection non-blocking.
SDL-Hercules-390/hyperion pull request #379
Opened 2021-03-23 03:16 UTC by mtalexander

The device lock is held when this call is made and if it blocks
things go down hill in a hurry.  According to the Linux select(2)
man page a call to recv may block even a previous call to select
says it shouldn't.  This has also been seen on MacOSX.

This fixes issue 377

2021-03-23 04:16 UTC, Fish-Git reviewed
Looks fine to me, Mike!

The _only_ questionable change I could see is your call to "socket_set_blocking_mode" in the "else" block immediately following the existing "recv_1052_data" call. Since the socket for 1052 devices already starts out in blocking mode (and I don't see any code that sets it to non-blocking mode), I don't see its utility. It's not accomplishing anything and thus can be removed.

BUT... since it's not hurting anything there's no real requirement to remove it. It just seems silly, that's all.

THANK YOU for taking the time and effort to help debug this problem, Mike! Much appreciated buddy!

Let me know if you want to re-submit your pull request without the redundant  1052 "socket_set_blocking_mode" call or not. If so, I'll wait for your updated pull request.

Otherwise if you don't want to bother, let me know that too and I'll go ahead and Approve your Pull Request as-is and merge it into our base!

WELL DONE!

2021-03-23 09:46 UTC, Juergen-Git commented
Hi Mike

fine for me. Concerning Fishs comment, I'd say, leave that redundant 1052 "socket_set_blocking_mode" in. One never knows, and I already had some very special surprises with this blocking/nonblocking/select kind of topics ;-)

Cheers
Jürgen

2021-03-23 22:33 UTC, mtalexander commented
Actually what I meant to do was put the call to set the socket non-blocking outside the if 3270 so that the 1052 socket was non-blocking when the recv is done on it.  This on the theory that the bug in select might affect it too.  I've pushed another commit to that branch.  If I understand how github works that will amend the pull request.

FWIW while I was testing this I happened to get the recv blocking failure on a telnet connection to a 1052.

2021-03-24 04:55 UTC, Fish-Git requested changes
> Actually what I meant to do was put the call to set the socket non-blocking outside the if 3270 so that the 1052 socket was non-blocking when the recv is done on it.

I see you have now made that change, yes, so now _both_ 3270 devices _and_ 1052 devices will have their sockets set to non-blocking mode immediately before calling their respective `recv_xxxx_data` function to perform the `recv` (which makes perfect sense since, as you just commented, even 1052's too can also encounter a `recv` blocking failure the same way it was happening for 3270's).

_**HOWEVER**..._

With the change you just made, doesn't that mean you now _also_ need to update the `recv_1052_data` function (near line 2780) _too?_ (to do the same thing you're currently doing in the `recv_3270_data` function?) I.e.:
```C
        if (HSO_EAGAIN == HSO_errno)
            // non blocking call and no data
            return 0;
        else
        {
            dev->sense[0] = SENSE_EC;
            return (CSW_ATTN | CSW_UC);
        }
```
I don't see that change anywhere in your pull request.

That is to say, if you need to do the above for 3270's as a result of temporarily setting the socket to non-blocking, now that you are _also_ setting 1052's sockets to non-blocking as well, don't you now also need to add the same `if (HSO_EAGAIN == HSO_errno) ...` code to the corresponding `recv_1052_data` function?

Oops? &nbsp; `:)`

2021-03-24 07:04 UTC, mtalexander commented
Ooops, indeed.  I remember thinking about this, but I didn't do it.  Sorry about that.  This just proves one of my favorite maxims: the simpler the change the more likely I am to screw it up. 

MTS can use a 1052 as a terminal, and it makes a decent terminal.  However it doesn't want an attention on every read.  I need to have a way to only send attention when a telnet break or equivalent is received.  Perhaps make this part of the noprompt option?  Or a new option?  Something to think about.

2021-03-24 07:12 UTC, Juergen-Git commented
>
> I need to have a way to only send attention when a telnet break or
> equivalent is received. Perhaps make this part of the noprompt option?
> Or a new option? Something to think about.
>
I strongly vote for a dedicated option. OS/360-MVT and MVS 3.8 both are not happy without those attentions ;-)

2021-03-24 12:29 UTC, Fish-Git approved these changes
Much better. Thanks.

2021-03-24 12:29 UTC, merged

2021-03-24 12:32 UTC, Fish-Git commented
Pull accepted and merged. Closing.

2021-03-24 13:51 UTC, wrljet commented
Will this affect APL\360?

2021-03-24 14:36 UTC, Juergen-Git commented
That's exactly the reason why I voted to leave the attentions in place: From a distance, I'd say, as long as those attentions remain as they are, APL\360 should be safe. But then: I anyway didn't take the local 1052 mods for APL\360 over into SDL Hyperion -- as long as this is not done, potential problems cannot become virulent (the other line of terminals (async 2741 et al) isn't affected at all by that commit).

2021-03-25 04:49 UTC, mtalexander commented
This pull request has nothing to do with attention interrupts or APL.  I mentioned attention interrupts in a comment, but that was probably a mistake since the change has no effect on them.  That's the subject for a separate discussion.  I agree that any change should not affect existing code.