Log format during shutdown (Issue 480)
SDL-Hercules-390/hyperion pull request #634
Opened 2024-02-23 22:30 UTC by JamesWekel

Here is a 2nd solution to fix two log format issues during shutdown [Issue 480:](https://github.com/SDL-Hercules-390/hyperion/issues/480)

1. duplicate log lines on non-Windows systems.
    
Issue related to logger processing and timing of shutdown `logger_unredirect()`. To fix the timing issue, a system `shutbegin` flag notifies `logger_thread()` that shutdown is beginning and to execute  `logger_unredirect()` before setting system shutdown flag. Timing is now controlled by `logger_thread()`.
          
2. interleaved log lines with two time stamps or missing a timestamp.

Update `logger_timestamped_logfile_write` to have a lock if timestamps are required. 

Tested using MVS TK5 startup/shutdown on Armbain Jammy (Ubuntu) on Raspberry Pi4 and Intel Nuc, and on Windows (Intel Nuc). Missing log lines _(e.g. 'hao_thread' ended)_ from previous 'bad' solution are included in the log. Not sure how to explicitly test problem #<span>2</span>. My test runs do not show any interleaved log lines but that doesn't imply the problem is resolved. 

Note: this solution does not make any attempt to resolve missing shutdown messages on the console.

I would appreciate further testing on other systems and any comments on the solution.

Thanks,
Jim

2024-02-24 04:39 UTC, Fish-Git requested changes
_ONE_ minor glitch...

In the `do_shutdown_now()` function, you need to move your declaration for `spincount` up to the top where your `loggersetshutdown` is being declared.

Yes, I know most modern versions of 'C' these days now allow you to declare variables anywhere before you reference them, but _older_ compiler versions do not. They require them to all be declared at the beginning of the function.

Other than that _ONE TINY THING_, everything else looks fine to me!

Make that one change and I'll be happy to accept your Pull Request!

Thank you for your continued contributions, James! &nbsp;`:)`

2024-02-24 06:18 UTC, JamesWekel commented
Fish,

Not a problem. I welcome the review and comments.

Jim

2024-02-24 08:17 UTC, Fish-Git approved these changes
Looks good to me!

2024-02-24 08:18 UTC, merged

2024-02-24 08:18 UTC, Fish-Git commented
Merged!

Thanks again, James!

2024-02-24 15:27 UTC, wrljet commented
We do still need to fully test it out on other systems, non-Linux, BSDs, macOS, etc.
I'll do some of them randomly.

2024-02-24 16:04 UTC, Fish-Git commented
> We do still need to fully test it out on other systems, non-Linux, BSDs, macOS, etc.
> I'll do some of them randomly.

Damn! I keep forgetting about that. I'll give it a try on my Kubuntu 21.10 system too.

2024-02-24 16:37 UTC, Fish-Git commented
FWIW, it seems to work just fine on both my Kubuntu 21.10 and my old CentOS 6.10 system too, both virtual machines running under VMware WorkStation (not that that makes any difference of course).

Should we close GitHub Issue #480 now?

2024-02-24 19:53 UTC, wrljet commented
I'd like to try it first on BSD and macOS before closing.

2024-02-25 22:32 UTC, wrljet commented
Works on macOS (Sonoma 14.4 Beta).

I'll try BSD next.

2024-02-29 18:42 UTC, Fish-Git commented
Well? Is BSD okay?

I'd like to close issue #480!

2024-03-01 16:05 UTC, wrljet commented
As far as this issue with the log output during shutdown is concerned, though, the changes to seem to work correctly on FreeBSD.

So I'd say we're good to go.

Bill

2024-03-01 17:11 UTC, JamesWekel commented
Bill: Thank you for all the testing, especially pointing out the problems with the first fix version.

Fish: thank you for the extra tests and reviewing the pull request.

Much appreciate all your support.

Jim

2024-03-01 19:00 UTC, Fish-Git commented
> The very recent change for that `processor stopped` message is confusing/breaking the tests?

Yep. &nbsp;It sure as hell is.

_**(F\*\*K!)**_

I jumped right on it and fixed it as soon as I got up this morning and saw your message, but also noticed another unrelated problem too that I introduced recently: the E7Prefix "Various CKD dasd I/O tests" test keeps failing because its shadow file isn't being deleted when the test finishes. &nbsp;`:(`

If you manually delete all shadow files in the tests directory before running your 'runtest', it works fine. But if you immediately try it again, it fails because the old shadow file is still there when the test starts even though its .tst script clearly said to discard it when the test was over! &nbsp;_(**`sf-a80 nomerge`**. The `nomerge` should be deleting the shadow file but for reasons unknown it's not.)_

I already have the fix for the "processor stopped" SNAFU ready to go and it does indeed correct the cause for all of the other 230+ failures. I'll go ahead and commit it ASAP.

_BUT..._ &nbsp; be aware that the other bug -- the 'sf' command's failure to delete the file when `nomerge` is specified -- will still remain, causing that one test to continue to fail whenever the old (previous) shadow file is still around when the test runs. So until I can find and fix it, just be sure no shadow files exist in the tests directory before running your tests and all tests should pass.

2024-03-01 19:01 UTC, Fish-Git commented
> As far as this issue with the log output during shutdown is concerned, though, the changes to seem to work correctly on FreeBSD.
> 
> So I'd say we're good to go.

Good. I'll go ahead and close issue #480 then. Thanks.

2024-03-01 20:09 UTC, Fish-Git commented
> _BUT..._   be aware that the other bug -- the 'sf' command's failure to delete the file when `nomerge` is specified -- will still remain, causing that one test to continue to fail whenever the old (previous) shadow file is still around when the test runs. So until I can find and fix it, just be sure no shadow files exist in the tests directory before running your tests and all tests should pass.

Fixed!

2024-03-01 21:57 UTC, wrljet commented
> > The very recent change for that `processor stopped` message is confusing/breaking the tests?
> 
> Yep.  It sure as hell is.
> 
> _**(F**K!)**_
> 
> I jumped right on it and fixed it as soon as I got up this morning and saw your message, but also noticed another unrelated problem too that I introduced recently: the E7Prefix "Various CKD dasd I/O tests" test keeps failing because its shadow file isn't being deleted when the test finishes.  `:(`
> 
> If you manually delete all shadow files in the tests directory before running your 'runtest', it works fine. But if you immediately try it again, it fails because the old shadow file is still there when the test starts even though its .tst script clearly said to discard it when the test was over!  _(**`sf-a80 nomerge`**. The `nomerge` should be deleting the shadow file but for reasons unknown it's not.)_
> 
> I already have the fix for the "processor stopped" SNAFU ready to go and it does indeed correct the cause for all of the other 230+ failures. I'll go ahead and commit it ASAP.
> 
> _BUT..._   be aware that the other bug -- the 'sf' command's failure to delete the file when `nomerge` is specified -- will still remain, causing that one test to continue to fail whenever the old (previous) shadow file is still around when the test runs. So until I can find and fix it, just be sure no shadow files exist in the tests directory before running your tests and all tests should pass.

Both issues tested and verifiied are fixed as of commit: https://github.com/SDL-Hercules-390/hyperion/commit/140a0cf89cff61e91b7bd9b1de5850b6c1ea9cd1

Tests work, and are "serially reusable".

2024-03-01 22:55 UTC, wrljet commented
Thank you, James, for your work and contribution!