Allow guest OS to handshake with spooled print/punch file ourput (resubmit)
SDL-Hercules-390/hyperion pull request #680
Opened 2024-08-28 21:04 UTC by bdenton

This PR adds a new handshake option to the printer and cardpch device handler. The purpose of which is to add new File-Open and File-Close CCWs for use by the guest OS to delineate spool file boundaries and properly name the files creates by Hercules. Updates to VM370CE v1.1.2 are included to integrate VM guests with this update.

This PR makes minor changes to the way the append option is processed.

cheers,
William Denton

(Resubmitting after rebasing branch to 'develop')

2024-09-03 00:23 UTC, Fish-Git requested changes
--------------------------------------------------------------------------------
PR#680 Allow guest OS handshaking with prt/pch socket devices
--------------------------------------------------------------------------------


#### DOCUMENTATION:


Where is the documentation for this new Hercules feature?


You will need to also provide the appropriately documentation updates
to our "hercconf.html" web page too, so users know to to use this new
feature. Not only the device statement option(s) and what they do, but
also the new CCW opcodes and how to use them. (As well as mentioning
that not all operating systems may support this feature.)



--------------------------------------------------------------------------------



NO TABS! Use *spaces* only.



Please use separate line for braces, e.g.:
```C
    if (cond)
    {
        whatever...
    }

    switch ()
    {
    }

    etc...
```




Get rid of all `WED` tags, and `/*BEGIN/END changes by WED:`, etc.
(NOT needed as git repositories maintain history of who changed each line over time)



--------------------------------------------------------------------------------

#### .gitignore:


I question the need for your additions to .gitignore.
Why do you feel they are needed?


--------------------------------------------------------------------------------

#### Fix change to msgenu.h:

```C
// reserve 01250 - 01299 for Generic device messages
#define HHC01250 "%1d:%04X %s: error in function %s: %s"
#define HHC01251 "%1d:%04X %s: option '%s' has been deprecated"
//efine HHC01252 - HHC01290 (available)
#define HHC01291 "%1d:%04X %s: writing to file %s"
#define HHC01292 "%1d:%04X %s: renaming output file %s to %s"
//efine HHC01293 - HHC01299 (available)
```

--------------------------------------------------------------------------------

#### printer.c:


`printer_query_device`:

  column alignment


--------------------------------------------------------------------------------

#### BOTH printer.c and cardpch.c:


`//WED: defer file open until first data xfer CCW              //WED`

Explain WHY. (i.e. justify the need). Or else just delete the code
altogether. Personally, I don't see the need for this. Just check
the "handshake" flag as needed.



Why did you replace `(dev->hnd->close)( dev );`???
DON'T call `xxxx_close_device()` directly. Use `(dev->hnd->close)( dev );` instead.
(`static int xxx_close_device( DEVBLK* dev );` fwd reference thus not needed.)



```C
  /* Handle the VM Handshake CCWs first since they           // WED
     will have an impact on how the output file              // WED
     gets opened on the first data xfer CCW                  // WED
  */
  switch (code) {                                            // WED
    . . .
```

I don't see the need for a separate `switch (code)` handling for the
`HANDSHAKE_OPEN` and `HANDSHAKE_CLOSE` opcodes. Just insert them anywhere
in the already existing `switch (code)` block. Preferrably at the end,
with a comment documenting their actual 0xF7 and 0xFF opcode values.



I also question the need for a seprate `ForHandshakeOnly()` function.
Logic should be placed directly into the CCW handling function instead.

**[Keep it simple](https://en.wikipedia.org/wiki/KISS_principle#:~:text=First%20seen%20partly%20in%20American,unnecessary%20complexity%20should%20be%20avoided.)**


--------------------------------------------------------------------------------

#### hstructs.h:


struct UROUTBLK:
  
add `typedef` and use it everywhere instead:

i.e. instead of:


    struct UROUTBLK
    {
      ...
    };
    #define UROUT(dev) ((struct UROUTBLK *)((dev)->dev_data))

    ...

    urOutBlk = (struct UROUTBLK*)dev->dev_data;

    (etc...)

do this instead:

    struct UROUTBLK
    {
      ...
    };
    typedef struct UROUTBLK     UROUTBLK;
    #define UROUT(dev) ((UROUTBLK*)((dev)->dev_data))

    ...

    urOutBlk = (UROUTBLK*)dev->dev_data;

    (etc...)



--------------------------------------------------------------------------------
#### hscutil.c:


_**Everywhere:**_ missing error check / message for all `malloc`s.



_**Everywhere:**_ No need to check for NULL before doing `free`.
Instead, just be sure to always SET to NULL AFTER freeing:

    free( urOutBlk->cmd_filename ); urOutBlk->cmd_filename = NULL;



_**Everywhere:**_ Replace all `strcpy/strcat` with `STRLCPY/STRLCAT` macro
instead to prevent overflow. Note that this requires using fixed length
char buffers (arrays). It also eliminates need to malloc/free.



_**Everywhere:**_ virtually ALL of your `uro...()` functions are ripe for
buffer overflow. Please fix `UROUTBLK` struct to use fixed length
buffers instead (not char*). Then replaace `strcpy/strcat` with
`STRLCPY/STRLCAT` macros instead.

Many of them are also passing superfluous arguments (e.g.`urotype`) that are not needed (not used anywhere). Please fix.


_**Everywhere:**_ Replace use of `sprintf` with `MSGBUF` macro instead
to prevent overflow. Note that this requires using fixed length
char buffers (arrays). It also eliminates need to malloc/free.


**`pushFileStack()`**:

  Please explain function's purpose better: Why are renames needed?
  Why can't you simply create a new file with a different suffix?
  Why rename all previously created files?
  
  `suffix + 1` is also not being limit checked. (Can't be incremented
  forever.)


--------------------------------------------------------------------------------

2024-09-03 21:19 UTC, bdenton commented
From the top...

1. HTML docs.. fine.. I'll give it a try although I am not a front-end developer...
2. TABS/spaces... this is blamed on VS... I'll see what I can do to fix them... might end up causing additional diffs due to inadvertent reformatting
3. Braces.. personal preference but I think this is, again, a VS artifact (and the fact that I am more recently a Java developer)
4. WED tags.. I'll get rid of them if you want.. they were there so my changes were clearly delineated when viewing the whole file
5. .gitignore... I didn't want the VS build target directories included in GIT
6. msgenu.h... ok.. I think this happened because my original development was against master
7. printer/cardpch - deferring the file open... just thought it would be better to not open the file on the attach/devinit... better to wait until the "real" fileid could  be built with input from the new FileOpen CCW. Also, this is a change that should apply regardless of the handshake setting.
8. printer/cardpch - dev close... I think my version is cleaner and clearer code... the close function was  the only time dev->hnd was used in either file... I just didn't see any reason for the indirection
9. printer/cardpch - separate switch... this was done for a couple of reasons: 1) the new CCWS should not cause any file open/close action 2) you will note that the new CCWs are also handled before most of the preamble before CCW handling (stop, etc)... I will grant you that the handling of device-stop could be cleaner.
10. printer/punch - ForHandshakeOnly()... just a habit of mine... when I need a piece of code more than once, I put it in a function rather than writing the same thing more than once.. this usually results in simpler, more readable code.
11. hstructs.h... ok.. I did notice that I was a bit inconsistent on addressing that structure
12. hscutil.c... (easy stuff first) pushFileStack()... the idea here is that the file named on attach/devinit is always the most recent generation (modeled after more log file naming schemes)... as far as placing a limit on the suffix, where would you suggest this gets configured? (practically speaking, I think the user would usually start trimming off the old files after something less than 100-ish versions)
13. hscutil.c... (elephant in the room) static vs dynamic strings... personally, I don't see where one is more or less prone to overrun. I have been very careful in calculating sizes for mallocs so as to never create an overrun situation. Changing everything to static allocations is going to realllly fluff up the code with all the checks to make sure the fixed allocation is not exceeded. Also, how do you suggest handling the situation when the size is exceeded? For instance, on Windows, there is a max path limit that is quite different from the limits on LInux

Sorry if this is  a little hard to follow... I couldn't figure out how to add my comments inline with your feedback 

cheers, William

2024-09-04 06:15 UTC, Fish-Git commented
> Sorry if this is a little hard to follow... I couldn't figure out how to add my comments inline with your feedback

I understand. You're new to GitHub.

The usual way is to _not_ to requote the entire post and insert your comment/response inline, but rather to simply response to each item individually by first selecting (highlighting) what the other person said with your mouse, and then pressing the 'r' key on your keyboard. This will copy that small part of what they said into your reply (preceded with a '> ' quote character). Then just type your response beneath that.

Then select the next part of their post and do the same thing again, etc, until you've eventually responded to everything you wanted to respond to.

OR... simply click the _**...**_ icon at the top-upper-right of the other person's comment and then select "Quote Reply" from the dropdown menu that appears.

More information: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-text

Hope that helps!

2024-09-04 07:35 UTC, bdenton commented
Yes, yes, I get all of that... I'm not that new to Github.. was just
wishing that there was a way to embed my comments/replys/rebuttals within
your feedback.

Do you need me to rework my prior reply to cut/paste the applicable parts
of your feedback into my response?

On Tue, Sep 3, 2024 at 11:15 PM Fish-Git ***@***.***> wrote:

> Sorry if this is a little hard to follow... I couldn't figure out how to
> add my comments inline with your feedback
>
> I understand. You're new to GitHub.
>
> The usual way is to *not* to requote the entire post and insert your
> comment/response inline, but rather to simply response to each item
> individually by first selecting (highlighting) what the other person said
> with your mouse, and then pressing the 'r' key on your keyboard. This will
> copy that small part of what they said into your reply (preceded with a '>
> ' quote character). Then just type your response beneath that.
>
> Then select the next part of their post and do the same thing again, etc,
> until you've eventually responded to everything you wanted to respond to.
>
> OR... simply click the *...* icon at the top-upper-right of the other
> person's comment and then select "Quote Reply" from the dropdown menu that
> appears.
>
> More information:
> https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-text
>
> Hope that helps!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SDL-Hercules-390/hyperion/pull/680#issuecomment-2328003884>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADHWPAQUXEPLGJVBXZJCBFDZU2QQPAVCNFSM6AAAAABNJCVAVSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRYGAYDGOBYGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-05 07:13 UTC, bdenton commented
BTW... VS2008 (your recommended build platform) appears to not like the `-nologo` argument on the `rc` commands in the build scripts...

2024-09-05 14:55 UTC, Fish-Git commented
> Yes, yes, I get all of that... I'm not that new to Github..

Oh. Sorry. I didn't know that. My apologies.

> was just wishing that there was a way to embed my comments/replys/rebuttals within your feedback.

Only members of the [SDL-Hercules-390](https://github.com/SDL-Hercules-390) GitHub Organization (i.e. only official SDL-Hercules-390 project developers with commit access to the repository) can "Edit" other's (i.e. anyone's) GitHub Issues comment, so yes, there _IS_ a way to do that. But unfortunately not for anyone else. Sorry!

The only way for you and others to do it is the way I explained: either "quote" (select and press 'R' key)  and reply to each item in the other person's comment, or else select "Quote Reply" from the comment box's '...' dropdown menu and then do it yourself manually.

If your '...' comment box dropdown menu doesn't have "Edit" in its list, then there's no way to do it that I know of.

Sorry! &nbsp;`:(`

2024-09-05 15:04 UTC, Fish-Git commented
#### _General FYI regarding email replies:_

I would very much appreciate it if you would _**not**_ respond/reply to GitHub via email.

I would much prefer that you instead respond/reply _directly_ via the GitHub web page itself:

* **[ht<span>tps</span>://github.com/SDL-Hercules-390/hyperion/pull/680](https://github.com/SDL-Hercules-390/hyperion/pull/680)**

When you reply **directly** via their web page, I can make minor edits to your reply so it is more readable (prettier) by editing the fonts being used, formatting of log messages, etc.

When you reply via email however, I cannot edit your reply (GitHub does not allow editing of emails), so oftentimes it is much harder (more difficult) to read.

GitHub also does not allow attachments in their email replies either, making it impossible to receive a file that may have been requested from you.

It is up to you whether or not you want to take the time to reply via their web page or continue to reply via email, but it is generally preferable that you reply directly via their web page instead. Especially if you need to attach a file that was requested from you.

Thanks for understanding.

2024-09-05 15:43 UTC, Fish-Git commented
> 1. HTML docs.. fine.. I'll give it a try although I am not a front-end developer...

Well, if you'd at least provide to us what you _want_ to be said in our web page, one of us (me most likely) will be happy to update the web page for you. But you didn't provide us with _any_ documentation at all! Documentation is important, William.

> 3\. Braces.. personal preference but I think this is, again, a VS artifact (and the fact that I am more recently a Java developer)

Brace usage is very controversial. But IMHO you should use the same style as what project is currently using.

> 4\. WED tags.. I'll get rid of them if you want.. they were there so my changes were clearly delineated when viewing the whole file

We can easily see what lines you changed via either GitHub itself (e.g. https://github.com/SDL-Hercules-390/hyperion/pull/680/files) or by using a good visual file/directory comparison tool such as [ExamDiff Pro](https://www.prestosoft.com/edp_examdiffpro.asp). IMO every serious developer should have a quality file comparison tool in their toolbox. It makes software development _SO_ much easier. I personally couldn't imagine doing software development without it.

> 5\. .gitignore... I didn't want the VS build target directories included in GIT

Directories and files which are not part of our repository are NEVER automatically included (added).  All files and directories that you want to be in your repository must be specifically added to it. So work directories with work files that just so happen to exist within the repository tree will never be automatically included, so don't worry about them.

> 7\. printer/cardpch - deferring the file open... just thought it would be better to not open the file on the attach/devinit... better to wait until the "real" fileid could  be built with input from the new FileOpen CCW.

Which I agree makes sense, but only when the `handshake` option is specified, yes? So just check if the `handskake` option is set, and skip that bit of code. Otherwise (`handshake` option _not_ specified), then proceed to do whatever Hercules was already doing. Yes?

> Also, this is a change that should apply regardless of the handshake setting.

I _**strongly**_ disagree! When the handshake option is not specified, then Hercules should behave exactly the same way it has behaved before: create the output file that is specified in the device statement.

> 8\. printer/cardpch - dev close... I think my version is cleaner and clearer code... the close function was  the only time dev->hnd was used in either file... I just didn't see any reason for the indirection

But other parts of Hercules call also call a device's "close" function too, and they do so via `(dev->hnd->close)( dev )`, because that's the only way they can reach it's close function if they're in a different module (DLL). Yes? What if at some point in the future a developer wishes to (or _needs_ do) change the name of the close function? With your way, they would need to change possibly _dozens_ of lines of code. By always using `(dev->hnd->close)( dev )` however, they would only need to change 2 and _ONLY_ 2 places: the function itself and the entry in the `DEVHND` struct. So the existing way (always using `(dev->hnd->close)( dev )`) is much easier to maintain.

It's just like using a `#define FOOBAR ...` constant: As long as you FOOBAR everywhere, then whenever you need to change its value to something else, you only need to change _ONE STATEMENT_: the `#define`. Otherwise you might need to change many, _MANY_ statements, which makes maintenance much harder and much riskier, since if you accidentally miss one or more places, you've suddenly broken things in a possibly _very hard to find way_.

> 9\. printer/cardpch - separate switch... this was done for a couple of reasons: 1) the new CCWS should not cause any file open/close action 2) you will note that the new CCWs are also handled before most of the preamble before CCW handling (stop, etc)... I will grant you that the handling of device-stop could be cleaner.

Again, this can be easily handled by just checking the `handshake` flag. Your way actually makes the code harder to understand and maintain and is completely unnecessary.

> 10\. printer/punch - ForHandshakeOnly()... just a habit of mine... when I need a piece of code more than once, I put it in a function rather than writing the same thing more than once.. this usually results in simpler, more readable code.

Yes, I'll grant you that. I do the same thing. But you need to weigh how big/complicated the function is, what its purpose it, and how many different places you need to use it. In this particular case, its purpose is to simply check the handshake flag and return command reject otherwise. Something that virtually every other CCW switch case already is already doing. So why hide that extremely short, simple, straightforward couple of lines of CCW processing code in a separate function that you need to pass parameters too? It'd be much simpler and more straightforward and thus easier to follow/understand if the _**3 freaking lines**_ of code would just be placed into the CCW switch case itself, just like all the other existing CCW switch cases. Please change.

> 12\. hscutil.c... (easy stuff first) pushFileStack()... the idea here is that the file named on attach/devinit is always the most recent generation (modeled after more log file naming schemes)... as far as placing a limit on the suffix, where would you suggest this gets configured? (practically speaking, I think the user would usually start trimming off the old files after something less than 100-ish versions)

Okay, I admit to misunderstanding your design. I should have examined your code more closely. The name of the file comes from the device statement, and your new OPEN/CLOSE  handshaking CCWs don't pass any data. They're both "immediate" CCWs that simply tell Hercules to close the current file and open a new one with the same name, but with a suffix if needed.

Because you didn't provide any documentation explaining what this new feature does (how it behaves) or how to use it, I was under the mistaken impression that the two new CCWs contained the name of the file as part of the CCW's data. (That is to say, I thought the name came from the guest via the new CCW!) Sorry. My bad.

Still, I don't see the need for any renames. Just 'do a stat` in a loop (bumping the suffix number each time) until a free (unused) filename is found, and use that. No need to call the same function recursively or do any renames IMO. Or am I missing something?

As far as a limit on the suffix goes, since it's just an integer (I missed that the first time! I thought it was an ASCII character A-Z or a string or something!), I see no need for _any_ limit at all. Just keep increasing it and let it overflow (wrap around) as needed. _HOWEVER_, to prevent problems, I suggest making it an _unsigned_ integer to prevent it wrapping around (overflowing) to a negative number.

> 13\. hscutil.c... (elephant in the room) static vs dynamic strings... personally, I don't see where one is more or less prone to overrun. I have been very careful in calculating sizes for mallocs so as to never create an overrun situation. Changing everything to static allocations is going to reallly fluff up the code with all the checks to make sure the fixed allocation is not exceeded.

Nope. We have easy to use macros for that (`STRLCPY`, `STRLCAT` and `MSGBUF`), so you don't need to calculate anything.

With dynamic strings, yes, you must manually calculate everything yourself (AND, for safety, pass the allocated length of that dynamic string buffer to each function that needs to update it, which you're not doing).

But for fixed-length static char string buffer arrays, it's easy peasy _(and SAFE!)_ when you use `MSGBUF`, `STRLCPY` and `STRLCAT`. Please use them

> Also, how do you suggest handling the situation when the size is exceeded? For instance, on [...]

2024-09-05 19:26 UTC, bdenton commented
> > 7. printer/cardpch - deferring the file open... just thought it would be better to not open the file on the attach/devinit... better to wait until the "real" fileid could  be built with input from the new FileOpen CCW.
> 
> Which I agree makes sense, but only when the `handshake` option is specified, yes? So just check if the `handskake` option is set, and skip that bit of code. Otherwise (`handshake` option _not_ specified), then proceed to do whatever Hercules was already doing. Yes?
>
> > Also, this is a change that should apply regardless of the handshake setting.
> 
> I _**strongly**_ disagree! When the handshake option is not specified, then Hercules should behave exactly the same way it has behaved before: create the output file that is specified in the device statement.  
> 

My intent with the deferred open *and* the rename stuff **WAS** to change the default Hercules behavior. I think the esisting logic is wrong:
1. The code should not create a file without knowing that there is to be something put in it. 
2. The code should not ever unilaterally erase something that the user might still have use for.

These concerns have nothing to do with the handshake option.

> > 8. printer/cardpch - dev close... I think my version is cleaner and clearer code... the close function was  the only time dev->hnd was used in either file... I just didn't see any reason for the indirection
> 
> But other parts of Hercules also call a device's "close" function too, and they do so via `(dev->hnd->close)( dev )`, because that's the only way they can reach it's close function if they're in a different module (DLL). Yes? What if at some point in the future a developer wishes to (or _needs_ do) change the name of the close function? With your way, they would need to change possibly _dozens_ of lines of code. By always using `(dev->hnd->close)( dev )` however, they would only need to change 2 and _ONLY_ 2 places: the function itself and the entry in the `DEVHND` struct. So the existing way (always using `(dev->hnd->close)( dev )`) is much easier to maintain.
> 
> It's just like using a `#define FOOBAR ...` constant: As long as you FOOBAR everywhere, then whenever you need to change its value to something else, you only need to change _ONE STATEMENT_: the `#define`. Otherwise you might need to change many, _MANY_ statements, which makes maintenance much harder and much riskier, since if you accidentally miss one or more places, you've suddenly broken things in a possibly _very hard to find way_.  
> 

I was just thinking about **internal** calls to the close method. The `dev->hnd` technique is perfectly valid for external calls... and, like you pointed out, is the only way to do cross-DLL calls. Requiring internal linkages to do the same thing is just like saying that a browser behind a firewall can only access a website that is also behind the same firewall by using the public-facing IP address (go back outside to come back in).

As far as scope of change goes... any change needed to modify the close method name would still be localized to the single file.. How many times could the close method be referenced in a single file? The answer is three in this case.

> 
> > 12. hscutil.c... (easy stuff first) pushFileStack()... the idea here is that the file named on attach/devinit is always the most recent generation (modeled after more log file naming schemes)... as far as placing a limit on the suffix, where would you suggest this gets configured? (practically speaking, I think the user would usually start trimming off the old files after something less than 100-ish versions)
> 
> Okay, I admit to misunderstanding your design. I should have examined your code more closely. The name of the file comes from the device statement, and your new OPEN/CLOSE handshaking CCWs don't pass any data. They're both "immediate" CCWs that simply tell Hercules to close the current file and open a new one with the same name, but with a suffix if needed.
> 
> Because you didn't provide any documentation explaining what this new feature does (how it behaves) or how to use it, I was under the mistaken impression that the two new CCWs contained the name of the file as part of the CCW's data. (That is to say, I thought the name came from the guest via the new CCW!) Sorry. My bad.
> 

I did provide what I thought was useful documentation in the `readme/README.VMHANDSHAKE` file.

The FileOpen CCW *does* pass in the desired file name. It is not necessarily an "immediate" command. I call your attention to the 3211 x'FB' CCW "Load UCSB".

> Still, I don't see the need for any renames. Just 'do a stat` in a loop (bumping the suffix number each time) until a free (unused) filename is found, and use that. No need to call the same function recursively or do any renames IMO. Or am I missing something?
> 

The renames are done to create a push-down stack of files with the most recent on the top and having the same name as given in the `device`/`devinit` statement (maybe modified by handshake CCW)

>
> As far as a limit on the suffix goes, since it's just an integer (I missed that the first time! I thought it was an ASCII character A-Z or a string or something!), I see no need for _any_ limit at all. Just keep increasing it and let it overflow (wrap around) as needed. _HOWEVER_, to prevent problems, I suggest making it an _unsigned_ integer to prevent it wrapping around (overflowing) to a negative number.  
>

You really think thee is a danger of having the suffix wrap around 2**31??
 
> > 13. hscutil.c... (elephant in the room) static vs dynamic strings... personally, I don't see where one is more or less prone to overrun. I have been very careful in calculating sizes for mallocs so as to never create an overrun situation. Changing everything to static allocations is going to reallly fluff up the code with all the checks to make sure the fixed allocation is not exceeded.
> 
> Nope. We have easy to use macros for that (`STRLCPY`, `STRLCAT` and `MSGBUF`), so you don't need to calculate anything.
> 
> With dynamic strings, yes, you must manually calculate everything yourself (AND, for safety, pass the allocated length of that dynamic string buffer to each function that needs to update it, which you're not doing).
> 
> But for fixed-length static char string buffer arrays, it's easy peasy _(and SAFE!)_ when you use `MSGBUF`, `STRLCPY` and `STRLCAT`. Please use them
> 
> > Also, how do you suggest handling the situation when the size is exceeded? For instance, on Windows, there is a max path limit that is quite different from the limits on Linux.
> 
> `MAX_PATH`. Or `PATH_MAX` if you prefer. Either one. They're each #defined to the same value depending on which platform Hercules is being built on. It's called "portable code".

One big problem I have with this is that there are no warnings given  to the user when data is getting truncated. Of course, I could always make the static fields big enough to avoid any sort of truncation and let the filesystem reject the open requests if it is too long

2024-09-06 21:20 UTC, Fish-Git commented
> > > 7. printer/cardpch - deferring the file open... just thought it would be better to not open the file on the attach/devinit... better to wait until the "real" fileid could  be built with input from the new FileOpen CCW.
> > 
> > Which I agree makes sense, but only when the `handshake` option is specified, yes? So just check if the `handshake` option is set, and skip that bit of code. Otherwise (`handshake` option _not_ specified), then proceed to do whatever Hercules was already doing. Yes?
> > > Also, this is a change that should apply regardless of the handshake setting.
> > 
> > I _**strongly**_ disagree! When the handshake option is not specified, then Hercules should behave exactly the same way it has behaved before: create the output file that is specified in the device statement.
> 
> My intent with the deferred open _and_ the rename stuff **WAS** to change the default Hercules behavior. I think the existing logic is wrong:
> 
> 1. The code should not create a file without knowing that there is to be something put in it.
> 2. The code should not ever unilaterally erase something that the user might still have use for.
> 
> These concerns have nothing to do with the handshake option.

What business does it have being a part of your Pull Request then? You should create a separate GitHub ISSUE for this proposed enhancement, so it can be discussed with the other developers and either accepted or rejected on its own. You're going to need to remove this unrelated change to Hercules's existing behavior from your Pull Request if you hope to have it eventually accepted and merged. As it stands, I cannot in good conscience accept it as-is. &nbsp;Sorry! &nbsp;`:(`
&nbsp;
&nbsp;
&nbsp;





> > > 8. printer/cardpch - dev close... I think my version is cleaner and clearer code... the close function was  the only time dev->hnd was used in either file... I just didn't see any reason for the indirection
> > 
> > But other parts of Hercules also call a device's "close" function too, and they do so via `(dev->hnd->close)( dev )`, because that's the only way they can reach it's close function if they're in a different module (DLL). Yes? What if at some point in the future a developer wishes to (or _needs_ to) change the name of the close function? With your way, they would need to change possibly _dozens_ of lines of code. By always using `(dev->hnd->close)( dev )` however, they would only need to change 2 and _ONLY_ 2 places: the function itself and the entry in the `DEVHND` struct. So the existing way (always using `(dev->hnd->close)( dev )`) is much easier to maintain.
> > It's just like using a `#define FOOBAR ...` constant: As long as you FOOBAR everywhere, then whenever you need to change its value to something else, you only need to change _ONE STATEMENT_: the `#define`. Otherwise you might need to change many, _MANY_ statements, which makes maintenance much harder and much riskier, since if you accidentally miss one or more places, you've suddenly broken things in a possibly _very hard to find way_.
> 
> I was just thinking about **internal** calls to the close method. The `dev->hnd` technique is perfectly valid for external calls... and, like you pointed out, is the only way to do cross-DLL calls. Requiring internal linkages to do the same thing is just like saying that a browser behind a firewall can only access a website that is also behind the same firewall by using the public-facing IP address (go back outside to come back in).
> 
> As far as scope of change goes... any change needed to modify the close method name would still be localized to the single file.. How many times could the close method be referenced in a single file? The answer is three in this case.

Fine. I'll give you this one.
&nbsp;
&nbsp;
&nbsp;





> > > 12. hscutil.c... (easy stuff first) pushFileStack()... the idea here is that the file named on attach/devinit is always the most recent generation (modeled after more log file naming schemes)... as far as placing a limit on the suffix, where would you suggest this gets configured? (practically speaking, I think the user would usually start trimming off the old files after something less than 100-ish versions)
> > 
> > Okay, I admit to misunderstanding your design. I should have examined your code more closely. The name of the file comes from the device statement, and your new OPEN/CLOSE handshaking CCWs don't pass any data. They're both "immediate" CCWs that simply tell Hercules to close the current file and open a new one with the same name, but with a suffix if needed.
> > Because you didn't provide any documentation explaining what this new feature does (how it behaves) or how to use it, I was under the mistaken impression that the two new CCWs contained the name of the file as part of the CCW's data. (That is to say, I thought the name came from the guest via the new CCW!) Sorry. My bad.
> 
> I did provide what I thought was useful documentation in the `readme/README.VMHANDSHAKE` file.

Oh?! I completely missed that. My bad.

But this then raises the fact that your PR, as it currently stands, is _incomplete_ and missing some additional required changes. Yes, you did add the new README to the repository, but you failed to _also_ appropriately update all of the other _[already existing]_ files in the repository impacted by the addition of that new file.

For instructions on how to add a new file to our repository, please see the "[**Adding New Files to Hercules**](https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.ADDING.md)" README in the _"**HERCULES INTERNAL READMEs"**_ section of our primary (main) [README](https://github.com/SDL-Hercules-390/hyperion/blob/master/README.md).

For reference, you can also review commit 0468fd04fed78b1daafebbb10b6393c29970cefb ("Document MAKETAPE via README") to see the changes you're also going to have to add to your Pull Request.

_(p.s. Your new README also contains some syntax/formatting errors in it too. Here's my corrected version:)_

* [README.VMHANDSHAKE.zip](https://github.com/user-attachments/files/16912547/README.VMHANDSHAKE.zip)

_(The "**1. Changed append Option Semantics**" wording is also confusing to me. It's unclear to me WHEN the new behavior occurs: when the `handshake` option is also specified or when the `handshake` option is not also specified. BUT... since this unrelated change to existing Hercules behavior should technically be in a completely separate GitHub ISSUE (and NOT in your Pull Request) as already explained further above, the point is moot I guess. You should probably remove that entire item altogether. **PLEASE NOTE** too, that I did NOT do that in my above corrected version. I leave that to you.)_
&nbsp;
&nbsp;
&nbsp;








> The FileOpen CCW _does_ pass in the desired file name. It is not necessarily an "immediate" command. I call your attention to the 3211 x'FB' CCW "Load UCSB".

Yes, I see that mentioned (_**NOW!**_) in your README that, as I said, I completely missed during my original code review.
&nbsp;
&nbsp;
&nbsp;






> > Still, I don't see the need for any renames. Just 'do a stat` in a loop (bumping the suffix number each time) until a free (unused) filename is found, and use that. No need to call the same function recursively or do any renames IMO. Or am I missing something?
> 
> The renames are done to create a push-down stack of files with the most recent on the top and having the same name as given in the `device`/`devinit` statement (maybe modified by handshake CCW)

I don't like that. I don't think that should be changed. It's counter-intuitive to me. But then once again, this is NOT something that should be part of your PR. It should be in a completely separate GitHub ISSUE it can be discussed with the other developers.
&nbsp;
&nbsp;
&nbsp;






> > As far as a limit on the suffix goes, since it's just an integer (I missed that the first time! I thought it was an ASCII character A-Z or a string or something!), [...]

2024-09-07 22:36 UTC, bdenton commented
I am cancelling this PR and going back to playing in my own sandbox.. At some point I might create another branch with all the "objectionable" code ripped out but for now,  the hassle of trying to share my work here is just too much.

2024-09-07 22:36 UTC, closed without merging