Add code to emulate a HIM device to connect MTS to the Internet
SDL-Hercules-390/hyperion pull request #689
Opened 2024-10-26 20:02 UTC by mtalexander

Emulate a Host Interface Machine (HIM) which is used to connect the Michigan Terminal System (MTS) to the Internet.

2024-10-27 04:48 UTC, Fish-Git commented
THANK YOU, Mike! I will try to review your Pull Request and provide you with feedback as soon as possible,

2024-10-28 00:16 UTC, Fish-Git commented
_**\*\* FYI \*\*** &nbsp; &nbsp; (mostly for myself):_

Tom has asked me to cc him with whatever feedback I provide to Mike:

> -----Original Message-----
> From: Thomas Valerio [mailto:tjv@westwood-tech.com]
> Sent: Sunday, October 27, 2024 10:53 AM
> To: "Fish" (David B. Trout)
> Cc: Mike Alexander
> Subject: Hercules - Multi-platform MTS/HIM device
> Importance: High
> 
> Fish,
>    I don't know if Mike communicated with you directly regarding his
> HIM device pull request, but he will be traveling from next Monday
> through November 17, and will probably have no or minimal Internet
> access and usually generally ignores his email when traveling anyway.
> 
>  So if you have any direct comment or criticism of the code before his
> return could you please cc me on any email that you might send directly
> to Mike.
> 
> -- Tom/

2024-11-16 20:50 UTC, Fish-Git commented
Sorry for the delay. I haven't gotten about you! I'm just having some serious personal issues right now.

2024-12-16 05:54 UTC, Fish-Git commented
CC: tjv@westwood-tech.com

> Any comment at all so far on this pull request and/or a guess on the ETM (expected time to merge)?

My apologies. Things were crazy at my household for this past month or more:

  * http://www.softdevlabs.com/news.html

I'm only now trying to get back into the swing of things.

I'm looking at your Pull Request right now. It looks like it's going to need a few _very minor_ changes.

One thing that would make it easier on me would be if you could pull/merge all of the latest develop branch changes that have been made since you first created your pull request into your HIM branch. That way I could more easily see _only_ your HIM changes by comparing your HIM branch again the _current_ develop branch. Do you think you could do that.

I've only spent the past few minutes reviewing your changes and so far I can say this about them: they look fine to me so far!

But give me another day (or two or three?) and I'll post a formal review for you.

Fair?

2024-12-16 08:48 UTC, Fish-Git requested changes
(CC: @tjvalerio Tom)

The only _required_ change is the one to the `UDP_sserver_listen_thread` function: lines 1823-1826 need to be moved to the beginning of the function. (I am using an older 'C' compiler and insist that it still be supported. Once I'm dead the other surviving members of the Hercules team/project can repeal that requirement as they wish, but as long as I'm alive, I'm going to insist that that requirement remain. Sorry!)

ALL OTHER CHANGES are purely cosmetic and optional. I removed a few blank lines here and there, moved a few opening braces on some `if` and `for` statements to be on their own separate line, inserted some opening/closing braces where some locks where being obtained/released to better see the lock's scope, etc, but that's about it! Everything else looked fine!

* [MTS.patch](https://github.com/user-attachments/files/18146980/MTS.patch) &nbsp; &nbsp; _(required and suggested changes)_

Just make that one minor required change, and I would be more than happy to merge your changes into Hercules! I think having MTS HIM device support would be an _excellent_ addition to Hercules!

_THANK YOU_ for your effort, Mike! &nbsp;`:)`

I look forward to seeing an updated Pull Request! &nbsp;`:)`

2024-12-22 00:07 UTC, mtalexander commented
Thanks for taking a look at this.  I've had a rough couple of months 
too, but I'm getting back to action now and will update that pull 
request and make your change as soon as I can.

2025-01-24 22:46 UTC, Fish-Git commented
@mtalexander Mike? Any progress? If possible, I would really like to see support for MTS make it into the next upcoming 4.8 release of Hercules!

2025-01-25 02:45 UTC, mtalexander commented
My shoulder has recovered to the point where I can work for a few hours 
before it tells me to stop.  With any luck I should be able to get 
something done this weekend.

Mike

On 24 Jan 2025, at 17:47, Fish-Git wrote:

> @mtalexander Mike? Any progress? If possible, I would really like to 
> see support for MTS make it into the next upcoming 4.8 release of 
> Hercules!
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/SDL-Hercules-390/hyperion/pull/689#issuecomment-2613540537
> You are receiving this because you were mentioned.
>
> Message ID: 
> ***@***.***>

2025-01-25 07:24 UTC, Fish-Git commented
> With any luck I should be able to get something done this weekend.

That would be great! &nbsp; BUT... your shoulder takes priority! &nbsp;`;-)`

Get well soon, Mike!

2025-01-27 08:40 UTC, Fish-Git approved these changes
Looks GREAT! Thanks, Mike! Pull Request APPROVED!  :))

2025-01-27 08:41 UTC, merged

2025-01-27 08:42 UTC, Fish-Git commented
Merged! :))

2025-01-28 18:39 UTC, tjvalerio commented
Thank you, Fish!!

2025-01-28 18:43 UTC, Fish-Git commented
Glad to do it! &nbsp;`:)`

Please confirm whether or not MTS now works okay for you with this version of Hercules!

2025-03-02 23:11 UTC, tjvalerio commented
Fish, MTS appears to work exactly as intended with the merged code.  In addition, another friend and I have had very good success in compiling and running the develop branch on ARM/Lineage OS/Debian on his pixel phone, with a relatively minor tweak to the makefile.  You may get a pull request for that makefile tweak as well, my friends name is Dennis Tokarski, and if you do I can vouch for the tweak, I watched it compile and run myself.

2025-03-03 16:01 UTC, Fish-Git commented
> You may get a pull request for that makefile tweak as well, my friends name is Dennis Tokarski, and if you do I can vouch for the tweak, I watched it compile and run myself.

10-4.